version: '3.7'
services:
  nginx:
    container_name: exo_devops_nginx
    build: docker/nginx
    volumes:
      - ./app/:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    ports:
      - "80:80"